spring:
  application:
    name: edge-service
server:
  port: 8081
security:
  oauth2:
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
zuul:
  ignored-services: '*'
  ignored-patterns: '/**/api/**'
  routes:
    user-service: '/user/**'
    article-service: '/article/**'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        timeout.enabled: false