spring:
  application:
    name: manju
server:
  port: 8080
security:
  oauth2:
    resource:
      user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo
    client:
      access-token-uri: https://accounts.google.com/o/oauth2/token
      user-authorization-uri: https://accounts.google.com/o/oauth2/auth
      client-id: ${clientId}
      client-secret: ${clientSecret}
      grant-type: code
      scope:
        - email
        - profile
      auto-approve-scopes: email, profile      
zuul:
  ignored-services: '*'
  routes:
    edge-service: '/api/**'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        timeout.enabled: false